### ISSUE TITLE
Adding localisation in Russian.

### ISSUE THREAD

**Issue by Atla01** [CodinGlitch/SimpleRadio#14]
I realise I probably should have created Pull Requests, but I got lazy, sorry for that. So I will attach the file ru_ru.json here. 
[ru_ru.json](https://github.com/CodinGlitch/SimpleRadio/files/14364019/ru_ru.json)

**Comment by CodinGlitch** [comment]
woah sick! yeah, it would probably be easier and cleaner to do a pull request, but this isn't much of a problem. thanks for the localization! i'll add it with the next update
