### ISSUE TITLE
Radio loses block data when broken

### ISSUE THREAD

**Issue by Meobra** [CodinGlitch/SimpleRadio#15]
Radio loses block data when broken and has to be retuned on the radiosmithing table.
P.S Such a cool mod, you have many amazing concepts for it and i cant wait to see them in-game :)

**Comment by CodinGlitch** [comment]
that's something i forgot to check when making the block drops for the radio, thanks for the report! and i'm glad you're enjoying the mod!

**Comment by CodinGlitch** [comment]
_should_ be fixed in 2.3.4
