### ISSUE TITLE
Request: The ability to stream audio from files or URLs

### ISSUE THREAD

**Issue by M0l1bden** [CodinGlitch/SimpleRadio#20]
After seeing the radio block, I immediately wanted to create my own radiostation with music. The only option is to hold the RMB and use the "voice" activation type with the Soundpad, that kinda sucks. The mod definitely needs the function of importing audio from Mp3 files or URL links to spotify, YouTube, and other sites.

**Comment by CodinGlitch** [comment]
i feel like uploading and playing audio files is best done by another mod, which i'll then just add support for

**Comment by M0l1bden** [comment]
> i feel like uploading and playing audio files is best done by another mod, which i'll then just add support for
All the addons for Simple voice chat, with such features that I found, were for Fabric.

**Comment by CodinGlitch** [comment]
ah.. if it's fabric only that might cause some problems, i'll think about it once i make transmitters, receivers and the like. maybe it'll be some module you can connect to a speaker to play audio, or connect to a transmitter to transmit it, i'm not sure yet

**Comment by M0l1bden** [comment]
I can only wait. I believe in the successful development of this mod
