### ISSUE TITLE
Radio and transciever play "starts broadcasting" sound upon deactivation (1.20.1, Fabric)

### ISSUE THREAD

**Issue by Hell0HighDefo** [CodinGlitch/SimpleRadio#21]
From what I've seen from digging around in the files for the mod, there is supposed to be a sound that plays when the transceiver / radio is deactivating, however, when those items are deactivated it replays the starting noise.

https://github.com/CodinGlitch/SimpleRadio/assets/100853907/da52d6d9-2be1-479f-a127-50104ef93b9a

**Comment by CodinGlitch** [comment]
oh wow—i'm not sure how i missed that, thanks for the fix!
