### ISSUE TITLE
Crash with new mod version 2.3.4

### ISSUE THREAD

**Issue by ghost** [CodinGlitch/SimpleRadio#31]
Crash when i try to load minecraft

Here log and debug 
[debug.log](https://github.com/user-attachments/files/15751092/debug.log)
[latest.log](https://github.com/user-attachments/files/15751093/latest.log)

**Comment by ghost** [comment]
There may be a conflict between Iron's spellbook and the new version of simple radio. This didn't happen before the update.

**Comment by GermanGamerMax** [comment]
I have the same issue, the log also ending with and I am also using iron's spells & spellbooks:

"[09Jun2024 10:03:10.294] [main/WARN] [mixin/]: @Redirect conflict. Skipping simpleradio.mixins.json:MixinLocalPlayer->@Redirect::simpleradio$aiStep(Lnet/minecraft/client/player/LocalPlayer;)Z with priority 1000, already redirected by mixins.irons_spellbooks.json:LocalPlayerMixin->@Redirect::addSlowdownCondition(Lnet/minecraft/client/player/LocalPlayer;)Z with priority 1000
[09Jun2024 10:03:10.294] [main/WARN] [mixin/]: @Redirect conflict. Skipping simpleradio.mixins.json:MixinLocalPlayer->@Redirect::simpleradio$aiStep(Lnet/minecraft/client/player/LocalPlayer;)Z with priority 1000, already redirected by mixins.irons_spellbooks.json:LocalPlayerMixin->@Redirect::addSlowdownCondition(Lnet/minecraft/client/player/LocalPlayer;)Z with priority 1000"

but my server runs fine, and doesn't seem to have any problems starting with both mods.

**Comment by CodinGlitch** [comment]
yeah, both my mod and irons are controlling the slowness when using an item, which seems to be the conflict, but i don't see how this should be crashing the game though. either way, ill be looking for maybe another method to use to avoid this conflict

**Comment by ghost** [comment]
i'm not a programmer, but maybe try to change priority to lower? Idk.

**Comment by CodinGlitch** [comment]
fixed in 2.3.5
