### ISSUE TITLE
Valkyrien Skies Ships Break Stuff

### ISSUE THREAD

**Issue by Brickmaster1** [CodinGlitch/SimpleRadio#34]
In the valkyrien skies mod I want to have a boat that has a radio on it but is not possible, because the blocks on ships are actually simulated in extremely far regions in valkyrien skies, but the game thinks that you are colliding with the ship in the actual spot in the world where your player is. This means the radios are too far for anything to function. If you could add compatibility with the valkyrien skies mod by tracking the audio from the location where the radio on the ship is actually displayed in the world instead of the regular behaviour when using the standard block position in the world, that would be nice. If this issue does not get a response in ~5 days I may consider forking and making compatibility, then PRing it to this repo as I have done for a few other mods.

**Comment by CodinGlitch** [comment]
unfortunately, making compatibility—especially for valkyrien skies—is not very high priority for me at the moment, so i would likely be getting to this after an inordinate amount of time, but if you are able to solve this feel free to make a PR and i'll gladly incorporate it!

**Comment by Brickmaster1** [comment]
Should probably close this now that it's a thing XD
