### ISSUE TITLE
[Bug] Issue with latest update

### ISSUE THREAD

**Issue by Atlas-Maker** [CodinGlitch/SimpleRadio#36]
the radio, speaker, and microphone aren't working as of the latest update
the radio and speaker aren't putting out any sound and talking near the mic can't be heard even with a transceiver 
this still happened even with a fresh install of the mod on its own

- Minecraft Version: [1.20.1]
- Simple Radio Version: [2.3.5]
- Mod Loader: [Forge]

**Comment by CodinGlitch** [comment]
oh my god i can't believe it i forgot to invert a check and broke the entire mod

**Comment by CodinGlitch** [comment]
should be fixed in 2.3.6
