### ISSUE TITLE
[Crash] SimpleRadio Failed to load correctly

### ISSUE THREAD

**Issue by AqueleHaru** [CodinGlitch/SimpleRadio#39]
**Describe the bug**
Crash on startup

**To Reproduce**
1. Download latest verison SR and Lexiconfig 
2. Try to start the game.

**Expected behavior**

**Screenshots**

**Version and Mod Loader:**
- Minecraft Version: 1.20.1
- Simple Radio Version: 2.3.6
- Mod Loader: Forge

![image](https://github.com/CodinGlitch/SimpleRadio/assets/61639486/0157911c-8963-480a-9f4d-442c715ec317)

**Comment by CodinGlitch** [comment]
downgrade lexiconfig to the previous version, the new simple radio version is supposed to support the new lexiconfig version, but its not released yet
