### ISSUE TITLE
Update to newer versions

### ISSUE THREAD

**Issue by SopsyHallow** [CodinGlitch/SimpleRadio#4]
Can this mod be updated to 1.20 pretty please?
I know that updating past 1.19.3 comes with changing some registries and other potential trouble ( i tried to do it myself but gave up after a few hours) but i hope it wont be too hard to do.
If not, i understand, thanks regardless

**Comment by CodinGlitch** [comment]
Updated to 1.20.2

**Comment by Liamgrayskull** [comment]
Sorry for the necro- is there any chance of a 1.20.1 port or is that not in the lines of possibility?

**Comment by CodinGlitch** [comment]
no worries, i'll see if i can get this and other versions up in the coming days, though i might not be able to work on it at the moment
