### ISSUE TITLE
Does not work with 1.20.4

### ISSUE THREAD

**Issue by ColinTheBossReal** [CodinGlitch/SimpleRadio#5]
CurseForge says that the most current version is compatible with 1.20.4, but when you try to load up a server with the mod it states "Mod 'SimpleRadio' (simpleradio) 2.1.2 requires version 1.20.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4"

**Comment by CodinGlitch** [comment]
after taking a look at this, it seems like this is a problem with the fabric version not properly checking for versions (supposed to be allowing 1.20.2-1.20.4, but only allows 1.20.2). hopefully i'll have a fix for this released sometime soon

**Comment by CodinGlitch** [comment]
should be fixed with v2.1.3
