### ISSUE TITLE
Requesting support for 1.20.1

### ISSUE THREAD

**Issue by NatSquared** [CodinGlitch/SimpleRadio#6]
This mod is great! I'd love to be able to use it with my modpack, which runs version 1.20.1 to keep with the majority of 1.20.x mods. Is there any chance of getting a compiled release jar for 1.20.1? I believe it would be useful to many others as well.
Thanks :)

**Comment by RedstoneGyerek** [comment]
It would be very good, because we can try and modify the code to allow 1.20.1, but i have a server on aternos, and it doesnt allow  custom mods to be uploaded

**Comment by CodinGlitch** [comment]
ported to [1.20.1](https://github.com/CodinGlitch/SimpleRadio/tree/1.20.1) and released for modrinth and curseforge
