### ISSUE TITLE
Dead Discord link and outdated wiki

### ISSUE THREAD

**Issue by VeonN4** [CodinGlitch/SimpleRadio#65]
Hi, so when I was looking at the wiki, I noticed that some of the items in the game are not in the wiki. and when I was looking for the discord server to ask, I found it in the README of the GitHub also in CurseForge and Modrinth too, but it seems all the link is dead.

**Comment by CodinGlitch** [comment]
i haven't found the time to update the wiki recently, so yeah it is quite outdated, but as for the discord links, i checked github, curseforge, and modrinth and they all appear to be valid to me, but ill include a fresh [discord link](https://discord.gg/wxXjXkMUbu) here just in case

**Comment by VeonN4** [comment]
> i haven't found the time to update the wiki recently, so yeah it is quite outdated, but as for the discord links, i checked github, curseforge, and modrinth and they all appear to be valid to me, but ill include a fresh [discord link](https://discord.gg/wxXjXkMUbu) here just in case

Alright, thanks mate!
