### ISSUE TITLE
Bug? Only 1 transceiver works.

### ISSUE THREAD

**Issue by Razor235T** [CodinGlitch/SimpleRadio#7]
On our server only 1 transceiver works. Other can receive audio, but they can't send audio. Is it only our server with our specific mods, or is it just a bug? We have simple voice chat mod installed and working. 1.20.1 Forge server.

**Comment by archonxgames** [comment]
Encountered this issue as well, it seems that each transceiver "binds" itself to the one who crafted it. If someone else tries transmitting using a transceiver made by somebody else, they are unable to send any messages across. The only way to circumvent it at the moment is to have each person craft their own transceivers.

**Comment by CodinGlitch** [comment]
you're probably right, the transceivers store an 'owner' in their tag which _should_ refresh when another entity holds it, but i didn't test it much so it's possible something is going wrong there.

**Comment by CodinGlitch** [comment]
after some more testing, it appears to potentially be an issue with holding multiple transceivers and then dropping it; when another player picks it up it'll remove the **old** users uuid from the listeners list, regardless of if they still have a transceiver in their inventory, can anyone confirm that dropping a transceiver for another player causes issues?

**Comment by CodinGlitch** [comment]
should be fixed with v2.1.3

**Comment by Razor235T** [comment]
I made transceivers and dropped to my friend, yep. But they start to work apparently if you hold RMB to speak and press ESC, it keeps holding even when you are in menu, and then it starts working, sometimes xD

**Comment by CodinGlitch** [comment]
that's a strange workaround, i guess the only thing to check now is if the new version actually fixes the issue
