### ISSUE TITLE
Issues with Crafting Transceiver

### ISSUE THREAD

**Issue by MixedUpContent** [CodinGlitch/SimpleRadio#8]
Currently using the most recently updated version to play on 1.20.2. The transceiver is unable to be crafted, even when the player has a receiving module, transmitting module, and speaking module, as well as the necessary ingredients for the crafting recipe. Crafting works on every other component (IE. modules, radios, etc).

![image](https://github.com/CodinGlitch/SimpleRadio/assets/159683462/47403c17-d6ab-4233-bb16-a899a3116329)

**Comment by MixedUpContent** [comment]
[ Image while all modules are in player's inventory]
![image](https://github.com/CodinGlitch/SimpleRadio/assets/159683462/91b07009-bda8-44f4-bbc0-393c50e9776a)

**Comment by CodinGlitch** [comment]
apologies for the confusion, i failed to change the recipe for the transceiver in the documentation after changing its recipe, which should be fixed now in the [transceiver page](https://github.com/CodinGlitch/SimpleRadio/wiki/Transceiver).
